### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by AlEmerich** [thebatu/foobar#1]
Hi, thank you for your great work.

I can't install this project, here is the output:

'''
>> make
make: *** No target specified
'''
Did you already had this problem ?

**Comment by thebatu** [comment]
Please install libgdx, libbats, libdelib and make :)

**Comment by AlEmerich** [comment]
Ok, nice, thank you, I close this issue ! I am using this repo every day, I hope the community will make it even bigger.
